services:
  libredb-studio:
    image: 'libredb/libredb-studio:0.18.2'
    environment:
      - ADMIN_PASSWORD=${LIBREDB_STUDIO_ADMIN_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    x-runtipi:
      is_main: true
      internal_port: 3000
x-runtipi:
  schema_version: 2
